"""product layer roles venues tiers tickets

Revision ID: 16e0db2e2abd
Revises: 4399ddd18aa9
Create Date: 2026-06-01 14:39:29.397569
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e0db2e2abd'
down_revision: Union[str, None] = '4399ddd18aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_city'), 'venues', ['city'], unique=False)
    op.create_table('price_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_tiers_event_id'), 'price_tiers', ['event_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checked_in_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_booking_id'), 'tickets', ['booking_id'], unique=False)
    op.create_index(op.f('ix_tickets_code'), 'tickets', ['code'], unique=True)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.add_column('events', sa.Column('description', sa.String(length=2000), nullable=False, server_default=''))
    op.add_column('events', sa.Column('organizer_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('status', sa.String(length=16), nullable=False, server_default='PUBLISHED'))
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_index(op.f('ix_events_organizer_id'), 'events', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_events_starts_at'), 'events', ['starts_at'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('ix_events_venue_id'), 'events', ['venue_id'], unique=False)
    op.create_foreign_key(None, 'events', 'venues', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'events', 'users', ['organizer_id'], ['id'])
    op.drop_column('events', 'venue')
    op.add_column('seats', sa.Column('section', sa.String(length=64), nullable=False, server_default=''))
    op.add_column('seats', sa.Column('tier_id', sa.Integer(), nullable=True))
    op.alter_column('seats', 'seat_number',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.create_index(op.f('ix_seats_section'), 'seats', ['section'], unique=False)
    op.create_foreign_key(None, 'seats', 'price_tiers', ['tier_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(length=16), nullable=False, server_default='USER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'seats', type_='foreignkey')
    op.drop_index(op.f('ix_seats_section'), table_name='seats')
    op.alter_column('seats', 'seat_number',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_column('seats', 'tier_id')
    op.drop_column('seats', 'section')
    op.add_column('events', sa.Column('venue', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_venue_id'), table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_starts_at'), table_name='events')
    op.drop_index(op.f('ix_events_organizer_id'), table_name='events')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_column('events', 'status')
    op.drop_column('events', 'venue_id')
    op.drop_column('events', 'organizer_id')
    op.drop_column('events', 'description')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_code'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_booking_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_price_tiers_event_id'), table_name='price_tiers')
    op.drop_table('price_tiers')
    op.drop_index(op.f('ix_venues_city'), table_name='venues')
    op.drop_table('venues')
    # ### end Alembic commands ###
