"""hold-pay-confirm lifecycle

Revision ID: 4399ddd18aa9
Revises: 665b10eb6af4
Create Date: 2026-06-01 04:09:12.011202
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4399ddd18aa9'
down_revision: Union[str, None] = '665b10eb6af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- data migration: old seat states -> new state machine ---
    # Rename the terminal sold state and drop any orphaned holds from the old
    # (pre-Hold-table) reservation mechanism.
    op.execute("UPDATE seats SET status = 'SOLD' WHERE status = 'BOOKED'")
    op.execute("UPDATE seats SET status = 'AVAILABLE' WHERE status = 'HELD'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_webhook_events_stripe_event_id'), 'processed_webhook_events', ['stripe_event_id'], unique=True)
    op.create_table('holds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_session_id')
    )
    op.create_index(op.f('ix_holds_event_id'), 'holds', ['event_id'], unique=False)
    op.create_index(op.f('ix_holds_expires_at'), 'holds', ['expires_at'], unique=False)
    op.create_index(op.f('ix_holds_status'), 'holds', ['status'], unique=False)
    op.create_index(op.f('ix_holds_user_id'), 'holds', ['user_id'], unique=False)
    op.create_table('hold_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hold_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hold_id'], ['holds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hold_items_hold_id'), 'hold_items', ['hold_id'], unique=False)
    op.add_column('booking_items', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.create_index('uq_active_booking_seat', 'booking_items', ['seat_id'], unique=True, postgresql_where=sa.text('active'))
    op.add_column('bookings', sa.Column('hold_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('payment_reference', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'bookings', ['hold_id'])
    op.create_foreign_key(None, 'bookings', 'holds', ['hold_id'], ['id'])
    op.add_column('seats', sa.Column('hold_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_seats_hold_id'), 'seats', ['hold_id'], unique=False)
    op.drop_constraint(op.f('seats_held_by_fkey'), 'seats', type_='foreignkey')
    op.create_foreign_key(None, 'seats', 'holds', ['hold_id'], ['id'])
    op.drop_column('seats', 'hold_expires_at')
    op.drop_column('seats', 'held_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('held_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('seats', sa.Column('hold_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'seats', type_='foreignkey')
    op.create_foreign_key(op.f('seats_held_by_fkey'), 'seats', 'users', ['held_by'], ['id'])
    op.drop_index(op.f('ix_seats_hold_id'), table_name='seats')
    op.drop_column('seats', 'hold_id')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='unique')
    op.drop_column('bookings', 'payment_reference')
    op.drop_column('bookings', 'hold_id')
    op.drop_index('uq_active_booking_seat', table_name='booking_items', postgresql_where=sa.text('active'))
    op.drop_column('booking_items', 'active')
    op.drop_index(op.f('ix_hold_items_hold_id'), table_name='hold_items')
    op.drop_table('hold_items')
    op.drop_index(op.f('ix_holds_user_id'), table_name='holds')
    op.drop_index(op.f('ix_holds_status'), table_name='holds')
    op.drop_index(op.f('ix_holds_expires_at'), table_name='holds')
    op.drop_index(op.f('ix_holds_event_id'), table_name='holds')
    op.drop_table('holds')
    op.drop_index(op.f('ix_processed_webhook_events_stripe_event_id'), table_name='processed_webhook_events')
    op.drop_table('processed_webhook_events')
    # ### end Alembic commands ###
